### ISSUE TITLE
`where.contains(...).first!` raises TypeError: Cannot visit Arel::Nodes::ContainsArray

### ISSUE THREAD

**Issue by mattbrictson** [dockyard/postgres_ext#172]
Upon upgrading from Rails 4.1.12 to 4.2.3, I began to see this error:

```
TypeError: Cannot visit Arel::Nodes::ContainsArray
```

The code in question uses the array contains operator, building a query like this:

```ruby
where.contains(:watchman_previous_ids => [id]).first!
# => TypeError: Cannot visit Arel::Nodes::ContainsArray
```

The strange thing is that `first` (non-bang version) works fine!

```ruby
where.contains(:watchman_previous_ids => [id]).first
# => nil
```

And `to_sql` works fine too!

```ruby
where.contains(:watchman_previous_ids => [id]).to_sql
# => SELECT "devices".* FROM "devices" WHERE "devices"."client_id" = 88 AND ("devices"."watchman_previous_ids" @> '{foo}')
```

Is this a Rails/Arel bug or am I doing something wrong here?

**Comment by edpaget** [comment]
Yes this is a bug with Arel. I wrote a patch for it here: https://github.com/rails/arel/pull/349

Basically the `first!` and `find!` methods use the generic arel sql visitor for their error messages instead of the sql visitors for their specific database connection. 

Since it doesn't look like anyone saw my Arel patch I may find a way to integrate into this gem instead.

**Comment by edpaget** [comment]
Hey that pull request was finally merged!
